default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: test1234
  pool: 5

development:
  <<: *default
  database: social_media_app_development


test:
  <<: *default
  database: social_media_app_test 